import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:google_sign_in/google_sign_in.dart';
final firestoreProvider = Provider((ref) => FirebaseFirestore.instance);
final authProvider = Provider((ref) => FirebaseAuth.instance);
final supabaseClientProvider = Provider((ref) => Supabase.instance.client);
final supabaseStorageProvider = Provider((ref) => Supabase.instance.client.storage);
final googleSignInProvider = Provider((ref) => GoogleSignIn());